name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    env:
      MONGO_URI: mongodb://root:example@127.0.0.1:27018/

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.12.0
      with:
        mongodb-username: root
        mongodb-password: example
        mongodb-db: test
        mongodb-port: 27018
    - run: npm ci
    - run: npm run build --if-present
    - run: npm run format
    - run: npm run test
